# Generated by Django 5.2.6 on 2025-09-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=100, unique=True)),
                ('teacher', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('ReportSent', 'ทำการส่งรายงานแล้ว'), ('Received', 'ได้รับรายงานแล้ว'), ('Forwarding', 'กำหลังส่งให้หน่วยงานที่เกี่ยวข้อง'), ('Pending', 'กำลังการตรวจสอบ'), ('Checked', 'ตรวจสอบเรียบร้อยแล้ว'), ('Completed', 'ทำการแก้ไขปัญหาเรียบร้อยแล้ว')], default='ReportSent', max_length=50)),
                ('respones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
