# Generated by Django 5.2.6 on 2025-09-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='respones',
            new_name='response',
        ),
    ]
